### ISSUE TITLE
1.20.1 LittleTiles Crash

### ISSUE THREAD

**Issue by Monocucuy** [FiniteReality/embeddium#25] opened 2023-09-16 19:18 UTC
Minecraft 1.20.1
Forge 47.1.47
[LittleTiles crash.txt](https://github.com/embeddedt/embeddium/files/12641435/LittleTiles.crash.txt)

**Comment by embeddedt** [comment] 2023-09-16 20:50
It's caused by LittleTiles referencing Sodium internals directly and needs to be fixed on their end. There is an issue open there (https://github.com/CreativeMD/LittleTiles/issues/888) and it appears the author provided links to a beta with the fix.

**Closed as completed by embeddedt** 2023-09-16 20:50 UTC
