### ISSUE TITLE
[1.19.2] Game randomly freeze

### ISSUE THREAD

**Issue by PinguiFabgeeklab** [FiniteReality/embeddium#300] opened 2024-05-20 18:35 UTC
### Bug Description

Bug randomly, not always - When Rubidium or Embeddium in this case are enabled, when I'm teleporting or walking to some areas or randomly, there are so much lags before to freeze / crash client-side. Same problem with all people of my server (excluded 1 on MacOS) with last or downgraded version of Embeddium.

The problem persist when i'm trying to connect to my server, i'm stuck at "Loading Terrain" and the game freeze and crash. I have sometimes to relaunch 3/4 times to connect well.

Forge 43.2.14
Minecraft 1.19.2
Mod list : screenshoot attached
![modlist](https://github.com/embeddedt/embeddium/assets/78692586/c2c5bc2f-d4a1-4d79-a8a1-d1f7ef3108d9)

### Reproduction Steps

- Teleport or walking around some areas or randomly
- Freeze of the game or crash
OR
- Trying to connect to the server
- Freeze of the game or crash

### Log File

[debug.log](https://github.com/embeddedt/embeddium/files/15380616/debug.log)

**Comment by embeddedt** [comment] 2024-05-20 18:39
This is pretty hard to narrow down if there are that many other mods present and it's random, but can you test with WaterFrames and WaterMedia disabled?

**Comment by PinguiFabgeeklab** [comment] 2024-05-20 19:17
It seems better without WaterFrames and WaterMedia disabled 

[debug.log](https://github.com/embeddedt/embeddium/files/15381040/debug.log)

**Comment by Nol-IsntUse** [comment] 2024-05-26 19:08
arent there two versions of embeddium there?

**Comment by embeddedt** [comment] 2024-05-30 21:26
Since this is the only report of this issue, it seems more likely that it's caused by another mod managing native memory incorrectly. Additionally, as of today, I'm no longer actively supporting 1.19.2, for various reasons including the age of the version, a lack of ability to make significant changes without compromising mod compatibility, and limited time for modding. Given that this is unlikely to be a bug in Embeddium, I'm closing this issue.

**Closed as not planned by embeddedt** 2024-05-30 21:26 UTC
