### ISSUE TITLE
fall apart

### ISSUE THREAD

**Issue by 1936268516** [FiniteReality/embeddium#288] opened 2024-05-05 02:30 UTC
### Bug Description

It crashes when you click on the video settings

### Reproduction Steps

It crashes when you click on the video settings

### Log File

[crash-2024-05-05_10.27.39-client.txt](https://github.com/embeddedt/embeddium/files/15211562/crash-2024-05-05_10.27.39-client.txt)

forge 1.20.1
They're all up-to-date.

**Comment by qznfbnj** [comment] 2024-05-05 02:38
Possibly Related Info:
![image](https://github.com/embeddedt/embeddium/assets/100760086/5c89021f-3983-4032-8af7-147190e785e7)
![image](https://github.com/embeddedt/embeddium/assets/100760086/3dd6f472-b978-4f70-bd91-f037cb01e27d)
![image](https://github.com/embeddedt/embeddium/assets/100760086/44cd63eb-0b20-41ec-a3dc-c990a6d9fcb0)
![image](https://github.com/embeddedt/embeddium/assets/100760086/409ba463-76fa-4062-9db8-44094d19d4d2)

**Comment by qznfbnj** [comment] 2024-05-05 02:39
Related Issue: #287

**Comment by embeddedt** [comment] 2024-05-05 16:46
Duplicate of #287 (which will be fixed in 0.3.18 today when I release it), will close to keep the issue tracker organized.

**Closed as not planned by embeddedt** 2024-05-05 16:46 UTC
