### ISSUE TITLE
[NeoForge 1.20.2] Crash when creating/ joining a world

### ISSUE THREAD

**Issue by TH3N3WN00B** [FiniteReality/embeddium#129] opened 2023-12-04 17:47 UTC
### Bug Description

Game crashes when creating and joining a world

### Reproduction Steps

Create a new instance of neoforge 1.20.2 - 20.2.86, add embeddium 0.2.10 and ferritecore 6.0.2, create a world

### Log File

Latest log: https://mclo.gs/ERRkanH

Latest Crash report (from the same log as above): https://mclo.gs/jL1vLT2

**Comment by embeddedt** [comment] 2023-12-04 18:26
This is caused by breaking changes in NeoForge and will be fixed with the next release.

**Comment by embeddedt** [comment] 2023-12-06 01:33
Fixed in 0.2.12.

**Closed as completed by embeddedt** 2023-12-06 01:33 UTC
Labels: bug, fixed in beta
