### ISSUE TITLE
Allthemods 9 suddenly crashes when Im playing.

### ISSUE THREAD

**Issue by Sajns** [FiniteReality/embeddium#45] opened 2023-09-30 09:02 UTC
Hey! When Im playing allthemods 9 the game can suddenly crash and according to the crash reports Java is going out of memory and I dont know how to fix this so I would be very thankful if I could get some help by someone.

[crash-2023-09-29_20.07.35-client.txt](https://github.com/embeddedt/embeddium/files/12774313/crash-2023-09-29_20.07.35-client.txt)

**Comment by embeddedt** [comment] 2023-09-30 12:19
Unfortunately this issue is more likely to be caused by another one of your mods... all this error says is that Embeddium couldn't allocate memory, which most likely means some other mod has used it up, or your system is running low on memory. You can try closing background programs, or reducing your render distance a bit.

**Closed as not planned by embeddedt** 2023-09-30 12:19 UTC
