### ISSUE TITLE
game crashes with this mod on neoforge 20.4.129+

### ISSUE THREAD

**Issue by nickademas** [FiniteReality/embeddium#181] opened 2024-01-27 02:34 UTC
### Reproduction Steps

download neoforge 20.4.129 or newer and embeddium and launch the game 

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14070709/latest.log)

**Comment by embeddedt** [comment] 2024-01-27 02:35
Known issue, it is caused by breaking changes in NeoForge. For now you can use the beta build: https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.4%2Fneoforge/Embeddium.zip

**Comment by embeddedt** [comment] 2024-01-29 20:24
Fixed in 0.3.0

**Closed as completed by embeddedt** 2024-01-29 20:24 UTC
Labels: fixed in beta
