### ISSUE TITLE
Pixel Texture problem (Embeddium 0.2.12, MC 1.20.1)

### ISSUE THREAD

**Issue by kazumadh** [FiniteReality/embeddium#131] opened 2023-12-07 07:46 UTC
There is something weird about the pixel texture of the blocks when I installed this mod, it's out of alignment.
1st picture is when this mod is installed, the second one is without it.
![texture out of alignmet](https://github.com/embeddedt/embeddium/assets/140326816/e2ca0fd2-0a6a-4236-9fc9-5ce4d3a8dbdd)
![texture alignment](https://github.com/embeddedt/embeddium/assets/140326816/7c87f7a9-e959-463a-8386-f7d2dfdd0a99)

**Comment by embeddedt** [comment] 2023-12-07 13:38
I can't reproduce this behavior.

* Does it occur without any other mods installed?
* If so, does it occur on Sodium with the same Minecraft version?
* What system setup are you using (GPU/CPU/OS)?

**Comment by kazumadh** [comment] 2023-12-07 14:29
> I can't reproduce this behavior.
> 
> * Does it occur without any other mods installed?
> * If so, does it occur on Sodium with the same Minecraft version?
> * What system setup are you using (GPU/CPU/OS)?

It's not hard. First install this mod, join a world (grass block superflat world is recommended), look straight down (to see the texture pixel clearly) and F2. Then uninstall this mod, join that world again, then F2 once more time. The most important thing is DO NOT MOVE THE CAMERA when taking screenshots, even the slightest. Look at these screenshots and compare (they must have the same resolution), you'll see the difference.

**Comment by embeddedt** [comment] 2023-12-07 14:34
Those are the exact steps I followed already (albeit without saving the screenshots) and as you can see, they are identical. There might be a slight 1 pixel shift in positions, but the texels are not different sizes like you have shown.

Embeddium:

![2023-12-07_09 31 14](https://github.com/embeddedt/embeddium/assets/42941056/17298ee0-b19a-4742-9eb4-2d8862af2dc6)

Vanilla:

![2023-12-07_09 32 15](https://github.com/embeddedt/embeddium/assets/42941056/2b03c23a-4546-4541-b928-b901148322e9)

**Comment by kazumadh** [comment] 2023-12-07 14:40
Hmm...Maybe I will experiment by installing this mod alone, then add others to see which causes this.

**Comment by kazumadh** [comment] 2023-12-20 02:29
I found the mod that caused this issue and I asked the author to fix it. But there is another issue about texture when installing this mod. Although it's still in alignment, but the last pixel at the right side of the block somehow became rectangle instead of square. Here's the comparison:
Embeddium:
![2023-12-20_09 05 22](https://github.com/embeddedt/embeddium/assets/140326816/16744946-5f26-4c85-b49d-b80ece5ffc4c)
(This screenshot was taken in Embeddium 0.2.13)
Vanilla:
![2023-12-20_09 08 20](https://github.com/embeddedt/embeddium/assets/140326816/387fa899-f233-4f27-b4a5-e38dcb06300a)

**Comment by embeddedt** [comment] 2023-12-20 02:30
Please try what I suggested here: https://github.com/embeddedt/embeddium/issues/147#issuecomment-1862004585, it might be the same underlying issue.

**Comment by kazumadh** [comment] 2023-12-20 02:36
I set "use_compact_vertex_format" to "false", as well as uninstalled Oculus, but nothing changed

**Comment by embeddedt** [comment] 2023-12-20 02:37
You also need to use the beta version linked in that message.

**Comment by kazumadh** [comment] 2023-12-20 02:52
Okay, it worked. Thanks so much, but I think you should contact Oculus's mod author about "use_compact_vertex_format" issue. Can we close this issue now?

**Comment by embeddedt** [comment] 2023-12-20 03:00
I'll close it once I release that beta as a full release.

**Comment by kazumadh** [comment] 2023-12-20 03:12
I hope the next version of Embeddium will prevent Oculus from breaking the block's texture.

**Comment by embeddedt** [comment] 2023-12-20 03:19
I cannot do that - Oculus is hardcoded to only support the compact vertex format (and not my full-precision format), this would need to be fixed on their end.

**Comment by kazumadh** [comment] 2023-12-20 03:25
I know, that's why you need to contact the Oculus's mod author to fix this once and for all, hope they won't refuse.

**Comment by embeddedt** [comment] 2023-12-22 02:41
The stone problem is the exact same underlying issue as #147, so I'll close this to keep the discussion in one place.

**Closed as completed by embeddedt** 2023-12-22 02:41 UTC
Labels: cannot reproduce
