### ISSUE TITLE
[1.19.2] Crash with Illuminations

### ISSUE THREAD

**Issue by Moecchiato** [FiniteReality/embeddium#257] opened 2024-04-03 23:36 UTC
### Bug Description

When I updated Embeddium and launched Minecraft it would just never end up loading the game. I waited for a long time but nothing ever popped up and was forced to close Minecraft through task manager. I downgraded the version and it would work just fine.

### Reproduction Steps

Use the latest version of Embeddium in a modpack and see that it would fail to load up Minecraft and get stuck.
downgrade to the previous version and then Minecraft would load.

### Log File

[debug-5.log](https://github.com/embeddedt/embeddium/files/14859518/debug-5.log)

**Comment by embeddedt** [comment] 2024-04-04 00:12
Is there a certain publicly available modpack I can add Embeddium 0.3.12 to and reproduce this problem in? There are over 300 mods in this instance based on the log file, and since it contains no errors this is not really actionable without something easy for me to test.

**Comment by Moecchiato** [comment] 2024-04-04 00:31
I have a modpack up called "Moe's Spooky Jump-scare Simulator" that can replicate this. It launches fine on the older version of Embeddium but if you update it, it won't load up anymore

**Comment by embeddedt** [comment] 2024-04-04 01:02
On my end it crashed with the newer version of Embeddium. It's strange that it froze for you rather than fully crashing; maybe there is a bug in your launcher. Anyway, I've fixed the cause of the crash. Can you let me know if the [beta build](https://nightly.link/embeddedt/embeddium/workflows/gradle/19.2%2Fforge/Embeddium.zip) works?

**Comment by Moecchiato** [comment] 2024-04-04 01:08
I can confirm the beta build works, thanks

**Comment by embeddedt** [comment] 2024-04-15 15:36
This fix is included in Embeddium 0.3.14.

**Closed as completed by embeddedt** 2024-04-15 15:36 UTC
Labels: bug, fixed in beta
