### ISSUE TITLE
Help with crash 1.20.1 any Embeddium version

### ISSUE THREAD

**Issue by BryanGun** [FiniteReality/embeddium#207] opened 2024-02-13 10:25 UTC
### Bug Description

I need help to find out why, I've tested several versions with no result, for Rubidium, even rubidium-0.6.5 works just fine :/

### Reproduction Steps

Just starting, crashes in the first loading before main menu

### Log File

[crash-2024-02-13_07.12.15-client.txt](https://github.com/embeddedt/embeddium/files/14259699/crash-2024-02-13_07.12.15-client.txt)

[latest.log](https://github.com/embeddedt/embeddium/files/14259714/latest.log)

**Comment by MarijnIsN00B** [comment] 2024-02-13 10:51
Valkyrien skies is incompatible with Embeddium atm, has to be fixed on VS's side

**Comment by SeagalKru** [comment] 2024-02-13 12:53
Greetings!
Updating your mod from embeddium-0.3.1+mc1.20.1.jar to embeddium-0.3.2+mc1.20.1.jar does not allow the game to load.
At the same time, I do not create a crash file, so I provide only the latest.log-file.
[latest.log](https://github.com/embeddedt/embeddium/files/14261756/latest.log)
Minecraft 1.20.1, forge 47.2.20.
Rolling back to the previous version of the mod (0.3.1) does not create a problem, the game starts.

Update:
![image](https://github.com/embeddedt/embeddium/assets/46864165/ab97dfdd-e829-412a-b91b-b6fbef4a1230)

**Comment by embeddedt** [comment] 2024-02-13 14:57
@SeagalKru Your issue is the same as this: https://github.com/embeddedt/embeddium/issues/206#issuecomment-1941692721

@BryanGun Your issue is caused by VS, as mentioned above, and can't be fixed on our end.

**Closed as not planned by embeddedt** 2024-02-13 14:57 UTC

**Comment by SeagalKru** [comment] 2024-02-14 16:13
> @SeagalKruВаша проблема такая же: [#206 (комментарий)](https://github.com/embeddedt/embeddium/issues/206#issuecomment-1941692721)
> 
I updated your mod to version 0.3.3, but the problem occurs again: the game closes on loading.
I take it you have to wait for the Oculus mod to update before updating your mod?
Now the latest version is 1.6.15.
Thank you.

**Comment by embeddedt** [comment] 2024-02-14 16:15
Yes, use 0.3.1 or wait for Oculus to release an update.
