### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by x-TheFox** [FiniteReality/embeddium#126] opened 2023-12-01 14:09 UTC
### Request Description

A Simple Checking system would be really good, 
yk, something that automatically disables the mod if its running on a server than a client
thanks, and sorry if this was dumb

**Comment by embeddedt** [comment] 2023-12-01 14:25
Which Minecraft version are you using?

**Comment by x-TheFox** [comment] 2023-12-01 15:57
i am pretty sure this will be a issue on every version but am using 1.16.5

**Comment by x-TheFox** [comment] 2023-12-01 16:00
also... sorry for derailing this but is there a feature that like reduces the resolution on mac's retina display?
am pretty sure sodium has it but i couldnt find that option... it would improve performance by ALOT on macbooks so it would be great if you could implement it  
something like this: https://www.curseforge.com/minecraft/mc-mods/retino-forge

**Comment by embeddedt** [comment] 2023-12-01 16:01
> i am pretty sure this will be a issue on every version but am using 1.16.5

I tested on a fresh 1.16 server and the game appears to start without errors even with Embeddium present.

> is there a feature that like reduces the resolution on mac's retina display?

This is out of scope for Embeddium to implement but I think that the Sodium Extra Forge ports include this option.

**Comment by x-TheFox** [comment] 2023-12-01 16:07
> I tested on a fresh 1.16 server and the game appears to start without errors even with Embeddium present.
>
Oh, that's weird I suppose it was another mod then
> This is out of scope for Embeddium to implement but I think that the Sodium Extra Forge ports include this option.
>
I have embedium extra and i doesn't seem to have it,I will look into others then
Thank you so much and sorry for the trouble

**Comment by x-TheFox** [comment] 2023-12-01 16:11
wait you made modernfix right?
https://bytebin.lucko.me/TFawQV5nTb
this crash report has the name of modernfix the most, thought you would know why..
should i create a issue on its github?

**Comment by embeddedt** [comment] 2023-12-01 16:48
I don't think that crash is caused by ModernFix; the name just shows up because it modifies one of the involved classes.

**Closed as completed by embeddedt** 2023-12-01 16:48 UTC
