### ISSUE TITLE
Embeddium corrupts Resource Packs with Connected Texture Blocks

### ISSUE THREAD

**Issue by kazumadh** [FiniteReality/embeddium#219] opened 2024-02-20 15:35 UTC
I installed Vanilla Tweaks Resource Pack with Connected Texture. When I install Embeddium, the texture of the blocks having Connected Texture get corrupted. In this video, I placed down iron blocks to form a line to make them connected, you can see the texture of the iron blocks keep flickering. 
Embeddium 0.3.4 Minecraft Forge 47.2.20 1.20.1
https://github.com/embeddedt/embeddium/assets/140326816/84600e2d-9cde-4434-adc5-64dafa9a5e23

**Comment by embeddedt** [comment] 2024-02-20 15:36
Try disabling the Compact Vertex Format in video settings.

**Comment by kazumadh** [comment] 2024-02-20 15:37
I disabled it, but nothing happens

**Comment by embeddedt** [comment] 2024-02-20 15:38
You can't disable it with Oculus installed (it looks disabled in settings, but is actually enabled, this is a bug I need to get around to fixing at some point).

**Comment by kazumadh** [comment] 2024-02-20 15:39
thanks

**Comment by betterworld-sjq** [comment] 2024-02-21 03:46
> You can't disable it with Oculus installed (it looks disabled in settings, but is actually enabled, this is a bug I need to get around to fixing at some point).

Sir, mine is still not working. My CTM feature is achieved with a fabric mod Continuity with Sinytra Connector running on forge. Would you mind taking a look somehow? Great gratitude to you!

**Comment by embeddedt** [comment] 2024-02-21 13:55
I believe you need Lazurite installed as well.

**Comment by betterworld-sjq** [comment] 2024-02-21 14:13
> I believe you need Lazurite installed as well.

Thanks!

**Comment by embeddedt** [comment] 2024-02-23 15:34
Closing as the issue is solvable with a config change and the root cause is not something we can easily fix.

**Closed as completed by embeddedt** 2024-02-23 15:34 UTC
Labels: sodium issue

**Comment by embeddedt** [comment] 2024-04-02 18:54
A potential fix for Vanilla Tweaks packs was added to release 0.3.12, for the record.
