### ISSUE TITLE
[1.18/1.19] Better Fps causes crash with 0.2.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [FiniteReality/embeddium#70] opened 2023-10-15 19:45 UTC
https://gist.github.com/P3rf3ctXZer0/e4a43d49eb917404e90cf69ef4eece98 crash in only triggered after play loads into world. You don't see the world but that is when the crash triggers.

**Comment by P3rf3ctXZer0** [comment] 2023-10-15 19:46
If you want to investigate 
[1.19.2-FFCM-S-rc10-12.0.5.zip](https://github.com/embeddedt/embeddium/files/12910518/1.19.2-FFCM-S-rc10-12.0.5.zip)

**Comment by embeddedt** [comment] 2023-10-15 19:47
This is caused by Better Fps - Render Distance having a mixin into Sodium internals, which will break randomly with Embeddium updates. You will need to remove that mod or use the Embeddium [beta](https://nightly.link/embeddedt/embeddium/workflows/gradle/19.2%2Fforge/Embeddium.zip) when it finishes compiling in a few minutes.

**Comment by P3rf3ctXZer0** [comment] 2023-10-15 19:47
Ah good :)

**Comment by embeddedt** [comment] 2023-10-15 20:51
Fixed in 0.2.3.

**Closed as completed by embeddedt** 2023-10-15 20:51 UTC
Labels: fixed in beta
