### ISSUE TITLE
[1.20.1] Updated Embeddium Causes Crashes with Mekanism

### ISSUE THREAD

**Issue by UnknownSerhan** [FiniteReality/embeddium#187] opened 2024-01-31 13:53 UTC
### Bug Description

After updating my embeddium from 0.2.16 to newer versions, it started to crash with Mekanism frequently. Downgrading Embeddium back to 0.2.16 fixed my problems.

### Reproduction Steps

Not exactly sure what triggers this bug, but I have Mekanism, Embeddium, Oculus and many more mods.

I have Mekanism Laser Tractor Beams placed down in my world and it randomly crashes when I am around them.

### Log File

[crash-2024-01-30_17.05.58-server.txt](https://github.com/embeddedt/embeddium/files/14112442/crash-2024-01-30_17.05.58-server.txt)

[2024-01-30-8.log](https://github.com/embeddedt/embeddium/files/14112501/2024-01-30-8.log)

**Comment by embeddedt** [comment] 2024-01-31 14:05
The crash appears to be caused by Mekanism, not Embeddium. Also, it occurs on the integrated server, which Embeddium doesn't really touch as it's a rendering mod. I would suggest reporting this to them; the code in that area doesn't look entirely safe at first glance.

**Comment by UnknownSerhan** [comment] 2024-01-31 14:18
Okay, and also after updating to new Embeddium, my world instantly crashes. I guess I have to open a new issue about that as it points to Embeddium and Oculus.

**Comment by embeddedt** [comment] 2024-01-31 14:19
As mentioned in the changelog Embeddium 0.3 includes a Sodium update which causes some addons to break. You will need to wait for those addons to update.

**Comment by UnknownSerhan** [comment] 2024-01-31 14:20
[crash-2024-01-31_17.17.33-client.txt](https://github.com/embeddedt/embeddium/files/14112807/crash-2024-01-31_17.17.33-client.txt)

Here is the report in case it helps.

**Comment by embeddedt** [comment] 2024-01-31 14:20
Yup, same crash, need to wait for Oculus to port the changes from Iris.

**Comment by UnknownSerhan** [comment] 2024-01-31 14:21
Alright thanks for the quick response and the help. I'll look into further more about the Mekanism crash issue as it never happened before, maybe something else is causing it to crash.

**Comment by Normal69** [comment] 2024-02-12 22:17
> Yup, same crash, need to wait for Oculus to port the changes from Iris.

Isn't it a typo?
[22:54:15] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Unsupported installed optional dependencies:
	Mod ID: 'oculus', Requested by: 'embeddium', Expected range: '(1.6.15,)', Actual version: '1.6.15'

**Comment by embeddedt** [comment] 2024-02-13 00:18
No. The latest version of Embeddium requires a strictly newer version than 1.6.15 (so the next Oculus update will work).

**Comment by embeddedt** [comment] 2024-02-23 16:32
I think the original issue is a possible race condition within Mekanism, or buggy logic in another mod. There is nothing Embeddium does that should be causing a crash on the server thread. Since no one else reported similar crashes after 0.2.16, I'm going to close this.

**Closed as not planned by embeddedt** 2024-02-23 16:32 UTC
