### ISSUE TITLE
Exception Access Violation on only one forge profile

### ISSUE THREAD

**Issue by Barerock** [FiniteReality/embeddium#324] opened 2024-06-24 03:15 UTC
### Bug Description

I've been attempting to fix this crash for a couple hours now and haven't gotten anywhere. I've disabled structure mods, thinking it was them, and now BetterEnd, which seems to think it's still installed. This occurs after loading the world completely.

I can fly around the world for a little bit, but eventually the game freezes and a few moments later the console either reports:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9247d4582, pid=8196, tid=23452
Or
Exit Code -1073741819, which occurs after an instantaneous crash when entering the world after complete load

I know these can be caused by GPU drivers being out of date, though I've updated mine to the latest. I've also updated Java fully, though perhaps I should backdate to Java 7. I've listed Java.exe in the Curseforge gamma bin in my graphics settings to ensure full use of my GPU, which works fine.

I have another Forge profile on the same Forge version with many of the mods I'm using in this pack, in fact, pretty much every mod besides a few exceptions from that pack is present in this one, so I can confidently rule out about 200 mods. I'm sure this is an incompatibility with something, but I doubt it's Entity Culling or Sound Physics Remastered, although I can/will test both of those, they're among the vetted mods.

That other pack runs more or less without issue, and I have a couple hundred hours in it. Removing Embeddium from this pack totally resolves the crashes, but of course removing other mods leads to the problem of not actually knowing when/where/how the crash will appear with surety. It may be alleviated by some removal, but still occur later.

Memory is fine, the pack sits at around 6000/8000, which I increased from a total of 6GB because it seemed to be maxing out. My CPU goes nuts with this pack, which I'm nervous about, but my GPU is chill at 67 C mostly.

Please ask if you want a full copy of any of these console logs, there are some weird and concerning errors, some are even fatal from ApexMods dev. I'm not sure how to force it to have an access violation vs the smaller exit code.

### Reproduction Steps

My mod list:
[A-ModList.txt](https://github.com/user-attachments/files/15949267/A-ModList.txt)
1. Install listed mods, and some others that don't seem to matter
2. Generate a world
3. Join the world
4. Either crash immediately on join or fly/walk around a bit
5. Crash after freeze from exception access violation

### Log File

[hs_err_pid8196.log](https://github.com/user-attachments/files/15949238/hs_err_pid8196.log)
This is the only log I can get.

Error reports in the console:
[log 1.txt](https://github.com/user-attachments/files/15949257/log.1.txt)

**Comment by Barerock** [comment] 2024-06-24 03:17
I believe Chunk Sending is present in this mod list, I deleted it before posting this.

**Comment by Barerock** [comment] 2024-06-24 03:24
Wow what a funny premature bug report. I _think_ it may have been Chunk sending... I'm very unsure. I've been in world for 3 minutes, the longest it's lasted. I will continue to observe, but that seems like a solution?

**Comment by embeddedt** [comment] 2024-06-26 02:08
If this is still happening, see if latest beta (https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip) helps, I added another tweak to work around issues on Nvidia cards. In general it's very hard to diagnose the cause of these crashes though.

**Comment by Barerock** [comment] 2024-06-26 02:11
This was being caused by Rethinking Voxels and Physics Mod pro ocean physics being incompatible with each other. You can't turn ocean physics off completely, so the colored lighting in Complementary style shaders crashes the game, or whatever. The GPU error was being caused by BCLib being run in a Forge environment, which isn't supposed to break it with Connector, but does.

Chunk Sending probably had something wrong with it, idk, I'll be testing it more as I reenable mods. Thanks!

**Comment by embeddedt** [comment] 2024-07-02 01:26
Closing as I don't think there is any direct fix I can make for this specific issue; the change I noted above *may* help with the general class of issues, and is released in 0.3.22.

**Closed as completed by embeddedt** 2024-07-02 01:26 UTC

**Comment by Barerock** [comment] 2024-07-02 01:28
Yeah, this hasn't occurred at all without RV enabled, so cheers. Hopefully PM will sort out their ocean physics stuff.
