### ISSUE TITLE
Incorrect block outlines

### ISSUE THREAD

**Issue by xbxbxb123** [FiniteReality/embeddium#322] opened 2024-06-23 05:11 UTC
### Bug Description

When Embeddium is installed, the outlines on selected blocks sometimes (seemingly at random) change to a strange pattern. There was once a different pattern than the one shown, it seems to be constant in a given session. The problem sometimes goes away at random, but comes back just as frequently.
![Image of the error taking place](https://github.com/embeddedt/embeddium/assets/25107898/21d3488d-56a1-4dbe-b188-082712248746)

### Reproduction Steps

Install Embeddium and keep looking at blocks until something randomly(?) goes wrong and the error happens. Possibly hardware specific? 
Graphics card:
NVIDIA GeForce GTX 1050 Ti 
Drivers: 
Nvidia Game Ready Driver Version 537.58 (I updated it to this version I saw was recommended after the game asked me to update my drivers to a list of versions including this one)

### Log File

[latest.log](https://github.com/user-attachments/files/15942606/latest.log)

**Comment by xbxbxb123** [comment] 2024-06-23 05:13
By "constant in a given session" I mean that the error happens at random, and the game will sometimes show the correct shape and sometimes not, and the incorrect shape it shows is always the same until I close and reboot the game

**Comment by embeddedt** [comment] 2024-06-26 02:06
Interesting. Can you give the latest beta for 1.21 (https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/21.0%2Fneoforge/Embeddium.zip) a shot and see if you can reproduce it anymore? I disabled a line rendering optimization that might have been the cause. It needs a redesign for 1.21 and I suspect it's not worth the effort to bother turning back on.

**Comment by xbxbxb123** [comment] 2024-06-26 07:12
That seems to have worked, I played for a few hours and didn't see the
issue at all

**Comment by embeddedt** [comment] 2024-07-02 01:22
Released in 1.0.2

**Closed as completed by embeddedt** 2024-07-02 01:22 UTC
Labels: bug, fixed in beta
