### ISSUE TITLE
Embeddium now crashes when loading a new world chunk.

### ISSUE THREAD

**Issue by vinnyg0621** [FiniteReality/embeddium#358] opened 2024-08-01 07:14 UTC
### Reproduction Steps

1. create a new world or go onto an existing world
2. have a new chunk render

### Log File

[crash-2024-07-31_21.06.14-server.txt](https://github.com/user-attachments/files/16451677/crash-2024-07-31_21.06.14-server.txt)
when creating a new world: 
[Uploading crash-2024-07-31_21.23.38-client.txt…]()

**Comment by embeddedt** [comment] 2024-08-01 21:33
The crash in this crash report has nothing to do with Embeddium; it comes from the integrated server, and seems to be related to Blueprint.

**Comment by uhloin** [comment] 2024-08-02 15:14
Same here with whining to Oculus

[crash-2024-08-02_19.14.06-server.txt](https://github.com/user-attachments/files/16472236/crash-2024-08-02_19.14.06-server.txt)

I found that my issue above (despite error message) have appeared with new version of Cyclic mod, but doesn't depend from the change of Embeddium (and Oculus) versions. So I reported to Cyclic developer.

**Comment by uhloin** [comment] 2024-08-02 15:26
Here is similar crash with version "embeddium-0.3.25+mc1.20.1.jar" 
T thought the problem is Chuk Loader mod and removed block for chunk keeping, but this what I've got, I haven't idea, what is happening.

**Comment by uhloin** [comment] 2024-08-02 15:26
[crash-2024-08-02_19.23.18-server.txt](https://github.com/user-attachments/files/16472351/crash-2024-08-02_19.23.18-server.txt)

**Comment by uhloin** [comment] 2024-08-02 16:11
I found that my issue above (despite error message) have appeared with new version of Cyclic mod, but doesn't depend from the change of Embeddium (and Oculus) versions. So I reported to Cyclic developer.

**Comment by embeddedt** [comment] 2024-08-11 02:28
Both crash reports here are from the integrated server so I do not think Embeddium is at fault in them; closing since there haven't been further reports of the original problem.

**Closed as not planned by embeddedt** 2024-08-11 02:28 UTC
