### ISSUE TITLE
Mana and Artifice and Embeddium don't get along.

### ISSUE THREAD

**Issue by levicc00123** [FiniteReality/embeddium#180] opened 2024-01-25 11:35 UTC
![2024-01-17_14 46 42](https://github.com/embeddedt/embeddium/assets/4361838/b53a0d15-4f74-468b-8700-46f704bd6170)

Minecraft: 1.20.1
Forge: 47.2.20
Mana and Artifice: 3.0.0.6
Embeddium: 0.2.18
OS: OpenSUSE Tumbleweed 20240123
Kernel: 6.7.1-1
graphics card info (from lspci -nnk):
`0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Tiger Lake-LP GT2 [UHD Graphics G4] [8086:9a78] (rev 01)
        Subsystem: Dell Device [1028:0ab0]
       Kernel driver in use: i915
`

**Comment by embeddedt** [comment] 2024-01-25 13:19
Could you please explain what blocks I need to place to reproduce this issue, as mentioned in the bug report template?

**Comment by levicc00123** [comment] 2024-01-25 15:14
The inscription table

**Comment by embeddedt** [comment] 2024-01-25 15:45
I'm not seeing a difference in how the block renders with or without Embeddium installed. Note that I have `experimentalForgeLightPipelineEnabled` set to true in `forge-client.toml`, as M&A recommended I do that on first startup.

Without:

![2024-01-25_10 43 18](https://github.com/embeddedt/embeddium/assets/42941056/cd50a7a1-535d-4179-b516-2fd1eb5da375)

With:

![2024-01-25_10 43 58](https://github.com/embeddedt/embeddium/assets/42941056/3883d069-a14c-4d8e-89d4-908788dbce91)

**Comment by levicc00123** [comment] 2024-01-25 16:44
Let me file a bug report with mithion then, and see what I can find out.

**Comment by embeddedt** [comment] 2024-02-12 19:15
Going to close this on our end because I don't think it's a problem with Embeddium.

**Closed as not planned by embeddedt** 2024-02-12 19:15 UTC
