### ISSUE TITLE
Embeddium Crash 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [FiniteReality/embeddium#204] opened 2024-02-11 20:00 UTC
### Bug Description

I have a crash of the game sometimes, the embendium is mentioned here. Can you tell me what the problem is?

---- Minecraft Crash Report ----

There are four lights!

Description: Accessing LegacyRandomSource from multiple threads

### Reproduction Steps

I have a large build of 280+ mods, so it's hard to reproduce.

### Log File

<html>
<body>

at net.minecraft.util.ThreadingDetector.m_199417_(ThreadingDetector.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,re:classloading,pl:mixin:APP:cupboard.mixins.json:ThreadingDetectorMixin,pl:mixin:A}
--
41 | at net.minecraft.world.level.levelgen.LegacyRandomSource.m_64707_(LegacyRandomSource.java:49) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
42 | at net.minecraft.world.level.levelgen.BitRandomSource.m_188503_(BitRandomSource.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
43 | at net.minecraft.client.multiplayer.ClientLevel.m_233612_(ClientLevel.java:383) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:embeddium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:krypton.mixins.json:client.fastchunkentityaccess.ClientWorldMixin,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:sanitydim.mixins.json:MixinClientLevel,pl:mixin:APP:bobby.mixins.json:ClientWorldAccessor,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:simplerpc.mixins.json:ClientLevelMixin,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinClientWorldCloudColor,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinClientWorldSkyColor,pl:mixin:A,pl:runtimedistcleaner:A}
44 | at net.minecraft.client.multiplayer.ClientLevel.m_104784_(ClientLevel.java:363) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:embeddium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:krypton.mixins.json:client.fastchunkentityaccess.ClientWorldMixin,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:sanitydim.mixins.json:MixinClientLevel,pl:mixin:APP:bobby.mixins.json:ClientWorldAccessor,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:simplerpc.mixins.json:ClientLevelMixin,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinClientWorldCloudColor,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinClientWorldSkyColor,pl:mixin:A,pl:runtimedistcleaner:A

</body>
</html>at net.minecraft.util.ThreadingDetector.m_199[41](https://mclo.gs/00Yw3Hp#L41)7_(ThreadingDetector.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,re:classloading,pl:mixin:APP:cupboard.mixins.json:ThreadingDetectorMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.LegacyRandomSource.m_64707_(LegacyRandomSource.java:49) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
	at net.minecraft.world.level.levelgen.BitRandomSource.m_188503_(BitRandomSource.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_233612_(ClientLevel.java:383) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:embeddium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:krypton.mixins.json:client.fastchunkentityaccess.ClientWorldMixin,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:sanitydim.mixins.json:MixinClientLevel,pl:mixin:APP:bobby.mixins.json:ClientWorldAccessor,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:simplerpc.mixins.json:ClientLevelMixin,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinClientWorldCloudColor,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinClientWorldSkyColor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104784_(ClientLevel.java:363) ~[client-1.19.2-20220805.130853-srg.jar%23721!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:embeddium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:embeddium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:krypton.mixins.json:client.fastchunkentityaccess.ClientWorldMixin,pl:mixin:APP:pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:sanitydim.mixins.json:MixinClientLevel,pl:mixin:APP:bobby.mixins.json:ClientWorldAccessor,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:simplerpc.mixins.json:ClientLevelMixin,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinClientWorldCloudColor,pl:mixin:APP:forge-badoptimizations.mixins.json:tick.MixinClientWorldSkyColor,pl:mixin:A,pl:runtimedistcleaner:A---- Minecraft Crash Report ----
// There are four lights!

Time: [2](https://mclo.gs/00Yw3Hp#L2)02[4](https://mclo.gs/00Yw3Hp#L4)-02-11 22:[5](https://mclo.gs/00Yw3Hp#L5)6:16
Description: Accessing LegacyRandomSource from multiple threads

**Comment by embeddedt** [comment] 2024-02-11 20:59
This crash is caused by another mod accessing the world's random number generator on the wrong thread. I recommend installing a tool like https://legacy.curseforge.com/minecraft/mc-mods/uwrad-forge and letting it crash a second time, it will provide more information.

Closing since it is not an Embeddium bug, but if you send a crash report with that mod installed here, I can take a look.

**Closed as not planned by embeddedt** 2024-02-11 20:59 UTC

**Comment by Krimatoria** [comment] 2024-02-11 21:02
> Этот сбой вызван тем, что другой мод обращается к мировому генератору случайных чисел не в том потоке. Я рекомендую установить такой инструмент, как https://legacy.curseforge.com/minecraft/mc-mods/uwrad-forge , и дать ему аварийно завершить работу во второй раз, это предоставит больше информации.
> 
> Завершаю, поскольку это не ошибка Embeddium, но если вы отправите отчет о сбое с установленным здесь модом, я смогу посмотреть.

Thank you very much) however, I will be able to check this only tomorrow when I play with friends on the server, but I will send the log here with that mod)
