### ISSUE TITLE
Crash with Feywild

### ISSUE THREAD

**Issue by Alrena** [FiniteReality/embeddium#234] opened 2024-03-16 01:24 UTC
### Bug Description

When a dwarven blacksmith structure, found underground, is gone near the game will crash. Presumably it's caused by the dwarven blacksmith mobs being spawned / loaded into memory.

### Reproduction Steps

Start any server with both Embeddium and Feywild, locate a dwarven blacksmith structure underground, move close enough to load it.

### Log File

Latest log:
https://gist.github.com/Alrena/6be1ad016d7230d16902d8abdec0b4fc

Crash Report:
https://gist.github.com/Alrena/81fb3fd516b3482d6f8100e7ecf83f68

**Comment by Alrena** [comment] 2024-03-16 01:25
I made a duplicate crash report on the Feywild issues github:
https://github.com/SaphieNyako/Feywild/issues/135

**Comment by embeddedt** [comment] 2024-03-16 01:28
Have you confirmed this crash doesn't occur with Embeddium removed in the exact same scene? The same null pointer exception looks like it would happen with vanilla's code...

**Comment by Alrena** [comment] 2024-03-16 22:39
After removing Embeddium I did a lot of testing for another crash, and checked to make sure the Feywild dwarven blacksmith wasn't still crashing. It's been fine for multiple hours and worlds tested, so I'm assuming it was a problem between the two mods.

**Comment by embeddedt** [comment] 2024-03-16 22:46
The crash doesn't happen in a standalone instance with Embeddium & Feywild if I follow your instructions.

![2024-03-16_18 45 12](https://github.com/embeddedt/embeddium/assets/42941056/dcdd0b9c-6c77-477d-b65a-77901e767844)

**Comment by Nolij** [comment] 2024-04-02 18:14
Closing this tomorrow if no updated reproduction steps are provided as we are unable to reproduce this issue. We can always re-open it if we receive updated reproduction steps after that.

**Closed as completed** 2024-04-06 03:01 UTC
Labels: cannot reproduce
