### ISSUE TITLE
Game Crashed after loading chunks

### ISSUE THREAD

**Issue by Iamuserin9112001** [FiniteReality/embeddium#264] opened 2024-04-14 14:22 UTC
According to the suspected mob, the embeddium (Ver: 0.3.12+mc1.20.1) was caused to game crashed due to chunkmesh error. It is happens both Curseforge and Modrinith.

https://mclo.gs/iKloQu8

[Modrinith: Forge 1.20.1]

**Comment by embeddedt** [comment] 2024-04-14 19:09
Duplicate of #111

**Closed as not planned by embeddedt** 2024-04-14 19:09 UTC
