### ISSUE TITLE
crash on launch with valkyrien skies + eureka

### ISSUE THREAD

**Issue by eldritch-cookie** [FiniteReality/embeddium#92] opened 2023-11-07 15:50 UTC
logs
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13282924/debug.log
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13282932/latest.log

i've also reported the issue on valkyrien skies github
https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/619

**Comment by embeddedt** [comment] 2023-11-07 15:52
This is caused by Valkyrien Skies accessing Embeddium internals, and needs to be fixed on their end.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/599

**Closed as not planned by embeddedt** 2023-11-07 15:52 UTC
