### ISSUE TITLE
1.20.1: just updated, now stuck in "joining game" screen and can't load in

### ISSUE THREAD

**Issue by muppetenergy** [FiniteReality/embeddium#289] opened 2024-05-05 06:47 UTC
### Bug Description

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:63) ~[forge-1.20.1-47.2.0-universal.jar%23323!/:?] {re:classloading}
-- MOD embeddium --
Details:
	Mod File: /C:/Users/((my name))/curseforge/minecraft/Instances/CL-c 0504/mods/embeddium-0.3.17+mc1.20.1-all.jar
	Failure message: Mod embeddium only supports textrues_embeddium_options 0.0.0-NOT-COMPATIBLE
		Currently, textrues_embeddium_options is 0.1.5+mc1.20.1
	Mod Version: 0.3.17+mc1.20.1
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE

![image](https://github.com/embeddedt/embeddium/assets/168618242/40045d49-f3c3-4c0a-a1b6-3aab0663eca5)

### Reproduction Steps

sorry i'm not sure how to answer this, I wasn't able to even get into the game.

**Comment by muppetenergy** [comment] 2024-05-05 07:12
I saw the changelog saying to remove the other embeddium related files. So, removed Textrues and embeddium extras
now I'm able to open the game, but I'm not able to get onto my server. 
The console for the server says I'm logged in, but this update seems to have messed something up? I've tried repeatedly, as well as restarting the server, and still hanging. 

![image](https://github.com/embeddedt/embeddium/assets/168618242/035dbb52-aff5-40cd-b5ff-0b94bdc6c468)

**Comment by muppetenergy** [comment] 2024-05-05 07:31
my launcher log is endlessly filling up with uhhh
admittedly I really don't understand this, but it's still hanging on that screen. It was at 700k messages and told me to clear it to avoid performance issues. 
hitting 'repair profile' in curseforge and restarting everything hasn't worked. 

The console for my server actually just showed that I was killed by a zombie, but my screen is still stuck on "Joining world" and wasn't even able to see where I was when I died :( 


![image](https://github.com/embeddedt/embeddium/assets/168618242/1fd447ed-b297-4981-a64d-75431ac97548)

**Comment by dooblykid** [comment] 2024-05-05 15:50
Same issue here.

**Comment by embeddedt** [comment] 2024-05-05 16:48
Please send the full log file.

**Comment by embeddedt** [comment] 2024-05-05 20:15
If you updated multiple mods, and Moonlight was one of them, this might be https://github.com/MehVahdJukaar/Moonlight/issues/217 (which may be solved by upgrading/downgrading Moonlight, apparently version 1.20-2.11.12 is known to be fine). A player who reported this in Discord shared their log and it appears to have the same errors as described in that issue.

**Comment by KingofJank** [comment] 2024-05-07 04:24
I am having the same issue.

**Comment by FunLay123** [comment] 2024-05-07 10:59
Try to delete Embedium Extra mod from your mods folder (if you have this mod).
If you have Oculus try to downgrade it to mc1.20.1-1.6.15a.

That things helped me to play on my server (had the same issue)

**Comment by muppetenergy** [comment] 2024-05-10 23:28
I had deleted all other embeddium related files, and was still stuck on the loading screen. tried even joining the game with the backup profile i'd made before I updated anything at all, and it still got stuck. 
so, ended up needing to have another player export their profile and use that and do a fresh profile. the game works now, ill keep an eye on updates to see if the issue is fixed. unfortunately don't have the log file D:

**Comment by Atomiiku** [comment] 2024-05-19 18:45
same thing here, stuck on loading game when trying to load a game, then when trying to create a game i get a crash, https://paste.ee/p/KoJDR heres my crashlog thingamathingy

**Comment by embeddedt** [comment] 2024-05-19 18:50
@Atomiiku Your crash appears to be caused by Shimmer.

**Comment by embeddedt** [comment] 2024-05-30 21:28
Closing as there was nothing changed in Embeddium that should prevent joining the game, and there haven't been further reports of this issue on GitHub or Discord, leading me to believe this was an issue caused by another mod that has since been fixed.

**Closed as completed by embeddedt** 2024-05-30 21:28 UTC
