### ISSUE TITLE
Visual Bug Near Torches with Embeddium

### ISSUE THREAD

**Issue by AxolotlAccount** [FiniteReality/embeddium#199] opened 2024-02-06 21:03 UTC
### Bug Description

Mounting a torch on a wall causes artifacts on the torch's block boundaries (not the boundaries of the torch itself). It is especially noticable when viewed while moving.
Tried disabling Use Compact Vertex Format, didn't fix the problem.
Uninstalled TexTrue's Embeddium Options and Embeddium (Rubidium) Extras, didn't fix the problem.
Uninstalling Embeddium fixed the problem.

Without Embeddium:
![without](https://github.com/embeddedt/embeddium/assets/17953179/638bdff9-2c5e-41ac-967b-8ba0318954b4)

With Embeddium:
![with](https://github.com/embeddedt/embeddium/assets/17953179/e37b72c4-504e-4cc3-a937-dd63add51331)

With Embeddium (marked to show what exactly is the problem)
![withmarked](https://github.com/embeddedt/embeddium/assets/17953179/b386b7f5-43dd-4939-8d5c-bcf0666eefb0)

### Reproduction Steps

1) Install Embeddium.
2) Mount a torch onto a wall.
3) Observe the torch. It is especially noticable when moving.

### Log File

https://gist.github.com/AxolotlAccount/b5cfce202f8f951fa7b0955f4f49a417

**Comment by embeddedt** [comment] 2024-02-06 21:19
Cannot reproduce with only Embeddium installed. There are far too many mods installed to guess what causes the issue; you will need to narrow down what mod is the problem. My educated guess would be Model Gap Fix, as it fiddles with texture coordinates.

**Comment by AxolotlAccount** [comment] 2024-02-07 09:57
I uninstalled Model Gap Fix and same issue still happens.

**Comment by JoeyTurncoat** [comment] 2024-02-10 06:33
Having this issue as well, disabled Model Gap Fix and disabled all texture packs. I've been trying to narrow the mods down but so far I haven't been able to find the problematic one.

**Comment by Terradeus280** [comment] 2024-02-13 16:53
I found the combination of mods that causes those white dots in blocks: Version 1.20.1 Forge
Citadel 2.5.3 - Curios 5.7.0 - embeddium 0.3.2+ - Farmers Delight 1.2.4 - Fruitful Fun 7.1.6 - Kiwi 11.5.3 - L_Ender_Cataclysm 1.90 - Lychee 5.1.9 - touhoulittlemaid 1.1.7 - Zeta 1.0.13 - Quark 4.0.435
Yes, ALL of them together. Remove any mod and the white dots dissapear, I tried removing Fruitful and L_ender and leaving only it's dependencies but you need those also or the bug doesn't happen.

An example picture, but moving you see it more clearly.
![Bug](https://github.com/embeddedt/embeddium/assets/126512959/b4d5e9c9-ab4e-42df-9843-d31d71546d10)

In this case i removed quark, but removing any of the mods above would fix it
![2024-02-13_13 32 03](https://github.com/embeddedt/embeddium/assets/126512959/9c13f5f8-8289-4831-b81b-547fe8795044)


Model Gap Fix also causes the same issue, and when i removed it and the issue persisted it was so strange. No clue why it also happens only when you have all of this mods together. I hope this can help. Also here's the log.

[latest.log](https://github.com/embeddedt/embeddium/files/14269648/latest.log)

**Comment by Terradeus280** [comment] 2024-02-13 16:55
But i think is a different bug, because the OP doesn't have Fruitful Fun neither Touhou Little Maid

**Comment by moninformateur** [comment] 2024-02-13 22:16
> Cannot reproduce with only Embeddium installed. There are far too many mods installed to guess what causes the issue; you will need to narrow down what mod is the problem. My educated guess would be Model Gap Fix, as it fiddles with texture coordinates.

I've provided a [modlist on Rubidium's issue page](https://github.com/Asek3/Rubidium/issues/380) where I'm always able to reproduce the issue. Note that it seems to be more visible in higher resolution monitors. It happens with a wide variety of mods.

The common variable is always Rubidium/Embedium. I'm not tech enough, but maybe it's linked to the light rendering since it only happens when there's a light source nearby?

**Comment by embeddedt** [comment] 2024-02-23 15:43
While the screenshot does not look *exactly* like #208, we have enough of an idea of what causes issues like this that we're pretty sure it is the same underlying cause. Since we can replicate the other issue with a test resource pack, but we haven't been able to reproduce this one at all, we're going to close this in favor of #208. It's very likely that whatever ends up fixing #208 will also fix this.

**Closed as not planned by embeddedt** 2024-02-23 15:43 UTC
Labels: cannot reproduce
