### ISSUE TITLE
Random crash after entering a world in 1.20.1 with mbeddium 0.3.12

### ISSUE THREAD

**Issue by ghost** [FiniteReality/embeddium#258] opened 2024-04-04 02:41 UTC
### Bug Description

Whenever I open or enter a newly created world it will just randomly crash.

### Reproduction Steps

Just have the same mods as me and enter a world. "Saving World" will appear.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14860614/latest.log)

**Comment by embeddedt** [comment] 2024-04-04 02:42
Duplicate of https://github.com/embeddedt/embeddium/issues/111

**Closed as not planned by embeddedt** 2024-04-04 02:42 UTC
