### ISSUE TITLE
[BUG] Several items appear dark after switching to Embedded

### ISSUE THREAD

**Issue by KakashoLin** [FiniteReality/embeddium#272] opened 2024-04-30 20:37 UTC
### Bug Description

Several items are darkened out making them hard to see, some items were Ars Nouvea's spellbook(all of them, and the dyed versions).

Other items affected were the Tomes of Blood which is based off the Ars Nouvea spell book.

ars_nouveau:novice_spell_book
ars_nouveau:aoorebtuce_spell_book
ars_nouveau:archmage_spell_book
tomeofblood:novice_tome_of_blood
tomeofblood:apprentice_tome_of_blood
tomeofblood:archmage_tome_of_blood

Issue doesn't appear to be listed above nor is there an active ticket for this issue. 

### Reproduction Steps

Put any of the effected items in your hotbar, and they will darken.hot bar

### Log File

There was no relevant information related to this issue in the latest.log file.

**Comment by embeddedt** [comment] 2024-04-30 20:46
This is a duplicate of https://github.com/embeddedt/embeddium/issues/75 - there is a compatibility issue between Ars Nouveau and ImmediatelyFast. The issue does not occur if only Embeddium and Ars Nouveau are installed.

**Closed as not planned by embeddedt** 2024-04-30 20:46 UTC
