### ISSUE TITLE
Crashing while open Video Settings (mouseClicked event handler)

### ISSUE THREAD

**Issue by Confiac1563** [FiniteReality/embeddium#337] opened 2024-07-06 09:04 UTC
### Bug Description

I tried accessing Video Settings to adjust a few things, but failed because I encountered a "mouseClicked event handler" error. I tried deleting Embeddium's config file but it didn't help
Crash Report about this problem
[crash-2024-07-06_15.58.40-client.txt](https://github.com/user-attachments/files/16115451/crash-2024-07-06_15.58.40-client.txt)

### Reproduction Steps

Version of mod: embeddium-0.3.24+mc1.20.4
Download it, put in "mods" folder and starting game, click o n Video Settings and... boom, it's crash :l

### Log File

Crash Report about this problem
[crash-2024-07-06_15.58.40-client.txt](https://github.com/user-attachments/files/16115451/crash-2024-07-06_15.58.40-client.txt)

**Comment by embeddedt** [comment] 2024-07-06 13:33
This is caused by Acedium assuming the translucency sorting setting is still in the Advanced tab (it isn't). The problem is easier to fix on Acedium's end. I've sent them a PR: https://github.com/ferriarnus/acedium/pull/16, the issue should be fixed once they merge it and release an update.

**Closed as completed by embeddedt** 2024-07-06 13:33 UTC

**Comment by Confiac1563** [comment] 2024-07-06 13:42
tysm
