### ISSUE TITLE
Incompatibility with Windowlogging

### ISSUE THREAD

**Issue by Bebrich** [FiniteReality/embeddium#380] opened 2024-09-05 18:43 UTC
### Bug Description

I'm running the latest versions of [windowlogging ](https://www.curseforge.com/minecraft/mc-mods/windowlogging)and embeddium available for 1.19.2, and I'm encountering some issues with rendering of windowlogged glass.
Glass is missing transparency when using the "Fancy" graphics option, and there is some mild Z-fighting visible.
![image](https://github.com/user-attachments/assets/74ac7c25-7526-4e2c-a67f-8761fe6f2306)

And if I were to switch to the "Fabulous" graphics option, transparency seems to not layer properly, and it looks noticeably . The Z-fighting persists.
Translucency sorting enabled:
![image](https://github.com/user-attachments/assets/eb6912ef-9398-4f2e-88d6-0530f4dc510d)

Translucency sorting disabled, there is some directionality to how it is rendered:
![image](https://github.com/user-attachments/assets/9c0e0baa-2d2e-43cb-ae0b-42857121e9e6)
![image](https://github.com/user-attachments/assets/3ad18e99-e352-437d-858f-7b9df143a16b)

It must be rendering something several times over.

### Reproduction Steps

Have both [windowlogging ](![image](https://github.com/user-attachments/assets/774e15e3-00f5-40a7-aa8e-83a7ab2e06af))and embeddium installed.

### Log File

[latest.log](https://github.com/user-attachments/files/16898893/latest.log)

**Comment by embeddedt** [comment] 2024-09-05 19:34
1.19.2 isn't supported anymore. Can this be reproduced on 1.20.1 or newer?

**Comment by Bebrich** [comment] 2024-09-06 08:04
Windowlogging isnt available for 1.20.1 yet unfortunately

**Comment by embeddedt** [comment] 2024-09-06 14:21
In that case I'd accept a pull request from a modder interested in fixing the issue for 1.19.2 and release an update if that happened, but I won't be fixing it myself.

**Closed as not planned by embeddedt** 2024-09-06 14:21 UTC
Labels: wontfix

**Comment by embeddedt** [comment] 2024-09-07 20:38
I looked into the cause of the issue out of curiosity; it's a bug in Windowlogged that an Embeddium optimization reveals. You can add `mixin.features.model=false` in `config/embeddium-mixins.properties` to work around it, but the proper fix would need to be done on Windowlogged's side (which is unlikely to happen, given it was last updated a year ago).
