### ISSUE TITLE
Obnoxious flickering ingame and within UI while using Embeddium 1.20.1

### ISSUE THREAD

**Issue by Ferynix** [FiniteReality/embeddium#153] opened 2023-12-21 16:12 UTC
### Bug Description

When I join a world, the game seemingly plays fine for a bit, and then randomly the screen will start flashing black. Glad I'm not epileptic, but it still hurts to look at. It makes the game completely unplayable. It doesn't happen on rubidium, but oculus doesn't work with it, so I cannot use it in this case.

Video of the bug in action: (Using youtube since github apparently cant handle anything over 10mb...)
https://youtu.be/oJ3I3ELyu4w

### Reproduction Steps

I was able to reproduce the bug with nothing but Forge 47.2.0 + Embeddium 0.2.13

In the video above I used Oculus and other visual mods, but I got the same flickering with just embeddium alone.

Seems the bug starts as soon as I start playing. I tap a keybind or open a GUI after a minute or two in the world and it starts going on the fritz. When you first open the world though it doesnt seem to flicker immediately.

### Log File

Log of the plain Forge + Embeddium Session:
[latest.log](https://github.com/embeddedt/embeddium/files/13743884/latest.log)

Additional Info:
Im on Windows 11 Pro (10.0.22621)
Im using the Nvidia Studio Driver (546.33) and am on an RTX 2070 Super

**Comment by embeddedt** [comment] 2023-12-21 16:14
Visual issues that occur with only Embeddium installed are usually caused by a GPU driver issue, which Embeddium cannot fix. Oftentimes, users report it is resolved by updating their graphics drivers.

https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility might be helpful.

**Comment by Ferynix** [comment] 2023-12-21 16:22
> Visual issues that occur with only Embeddium installed are usually caused by a GPU driver issue, which Embeddium cannot fix. Oftentimes, users report it is resolved by updating their graphics drivers.
> 
> https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility might be helpful.

I always keep my studio drivers up to date... (546.33 is far newer than the minimum version listed in that link)

And I cannot use the game ready drivers because theyre currently broken / having issues with other software in my computer.

This issue doesnt occur with rubidium or sodium on fabric, so that leads me to believe there is something wrong within embeddium. I would just use rubidium temporarily but oculus has basically ceased support for it so I have no options if I want my visual modpack to function properly.

**Comment by embeddedt** [comment] 2023-12-21 16:31
You could try deleting the Embeddium config files in `config`, in case you changed a setting that causes issues on your system. With default settings, the relevant code that interacts with the GPU should be exactly the same as Rubidium & Sodium...

In any case, Embeddium has been based on the same Sodium version for a few months, other users are not having this problem, and I cannot reproduce it myself... so it's going to be difficult/impossible for me to do much on my end aside from the general recommendation provided.

**Comment by Ferynix** [comment] 2023-12-21 18:00
> You could try deleting the Embeddium config files in `config`, in case you changed a setting that causes issues on your system. With default settings, the relevant code that interacts with the GPU should be exactly the same as Rubidium & Sodium...
> 
> In any case, Embeddium has been based on the same Sodium version for a few months, other users are not having this problem, and I cannot reproduce it myself... so it's going to be difficult/impossible for me to do much on my end aside from the general recommendation provided.

well, guess Im out of luck. I deleted all the config files and basically started from scratch with no luck.

I dont get why all this stuff is so problematic these days. I used to never have problems like this and now its like graphics / performance mods are breaking for me every other day

**Comment by embeddedt** [comment] 2024-01-14 22:18
The Sodium devs have suggested this might be linked to VSync/G-Sync settings - apparently this can have issues on Nvidia.

**Comment by embeddedt** [comment] 2024-01-14 22:24
Someone else suggested:

![image](https://github.com/embeddedt/embeddium/assets/42941056/cced10cd-ec6f-47cc-a008-0b6ee2430c5f)

**Comment by embeddedt** [comment] 2024-01-24 19:30
After further discussion in the Sodium discord, this seems to be an issue outside of our control; it can be reproduced in vanilla, too, with the right framerate & hardware setup. Appears to be related to either a Windows update, or driver update, but it's not entirely clear why. However, tweaking the settings suggested above seems to reliably prevent the issue.

**Closed as not planned by embeddedt** 2024-01-24 19:30 UTC

**Comment by opgyerek** [comment] 2024-12-16 14:45
> The Sodium devs have suggested this might be linked to VSync/G-Sync settings - apparently this can have issues on Nvidia.

This fixed my issue, just disable v-sync ingame and its all gone.

**Comment by Ferynix** [comment] 2024-12-16 14:49
> > The Sodium devs have suggested this might be linked to VSync/G-Sync settings - apparently this can have issues on Nvidia.
> 
> 
> 
> This fixed my issue, just disable v-sync ingame and its all gone.

I've been having this issue across many different drivers, and while vsync does make the issue less pronounced, I still experience flickering in full screen and whatnot

I've literally never managed to solve this and no one has ever offered a solution. I haven't played minecraft in quite a while as a result... It's rather unfortunate.

**Comment by LukasJef** [comment] 2025-12-27 13:04
After a while I found a solution:
So, the error is caused by Nvidia drivers. For nvidia gpu the fix is ​​simple.
1. Right click on desktop → NVIDIA control panel

2. Manage 3d settings

3. We need to set it Globally because curseforge, modrinth and other launchers have their own java.
     **1) Disable shader cache
     2) Set Threaded optimization to auto (If its not)
     3) Disable Vsync and Triple buffering (This is the most common problem)
     4) Set OpenGL rendering gpu to GPU you want to use
     5) Set "Power Management Mode" to "Prefer Maximum Performance"**
