### ISSUE TITLE
Smooth Lighting Issue on Xycraft Connected Textures

### ISSUE THREAD

**Issue by Dmac9244** [FiniteReality/embeddium#98] opened 2023-11-12 23:24 UTC
Smooth Lighting breaks on Xycraft connected textures such as the Immortal stones and trims, as shown in the screenshot below. Running on Minecraft 1.20.1, Forge version 47.2.0, Embeddium 0.2.9, and XyCraft Base, Override, and World .6.22.

![image_2023-11-12_180351813](https://github.com/embeddedt/embeddium/assets/6415980/ebd443dd-4873-4969-bbcd-6195753002d5)

With Oculus version 1.6.9 and Complementary shaders the issue is much more pronounced:

![image_2023-11-12_181702348](https://github.com/embeddedt/embeddium/assets/6415980/e72a2593-78d2-466c-836a-af5e2e6d89a2)

This does not occur on the upstream, 1.7.1a version of Rubidium, with/without Oculus, so I think it might be either a XyCraft issue that Rubidium is working around or an issue with embeddium solely.

**Comment by embeddedt** [comment] 2023-11-12 23:39
Can you confirm that https://nightly.link/embeddedt/embeddium/workflows/build-snapshot/20.1%2Fforge/Embeddium.zip fixes the issue?

**Comment by Dmac9244** [comment] 2023-11-12 23:57
The file you linked fixes the issue but causes a new one:

![image_2023-11-12_185551216](https://github.com/embeddedt/embeddium/assets/6415980/68974884-e441-4fd4-9940-b6a07cac9e1a)

With the shimmering in just about every XyCraft block you see on-screen.

**Comment by embeddedt** [comment] 2023-11-12 23:58
Disable "Compact Vertex Format" in Embeddium's video settings; this is probably caused by XyCraft not offsetting the layers of its blocks enough.

EDIT: Hmm, no, seems to happen even with it off.

**Comment by Dmac9244** [comment] 2023-11-13 00:02
That option seems to be disabled automatically by Oculus anyway, but I confirmed that it happens with/without Oculus installed, with/without Compact Vertex Format

**Comment by embeddedt** [comment] 2023-11-13 01:51
It seems to be a strange interaction between XyCraft's block model and Sodium's fix for [MC-138211](https://bugs.mojang.com/browse/MC-138211). For now, you can work around it by enabling Forge's experimental lighting pipeline in `config/forge-client.toml`, as this bypasses Sodium's fix.

**Comment by embeddedt** [comment] 2023-11-13 02:28
I've identified a way to avoid the problem in Embeddium itself, which will be included in the next release.

**Comment by Dmac9244** [comment] 2023-11-13 02:39
I can confirm the workaround works, thank you for the quick response!

**Comment by embeddedt** [comment] 2023-11-23 17:13
The fix has been released in Embeddium 0.2.10.

**Closed as completed by embeddedt** 2023-11-23 17:13 UTC
Labels: bug, has workaround, fixed in beta
