### ISSUE TITLE
When I enter a world with embeddium and oculus installed, the world does not load and crashes

### ISSUE THREAD

**Issue by Kailgroz** [FiniteReality/embeddium#167] opened 2024-01-04 01:17 UTC
### Bug Description

I was testing my modpack and I realized that I did not have Oculus installed, when I installed it together with Embeddium, (previously it occupied Rubidium) every time I entered a world the game crashed right after the loading screen

### Reproduction Steps

When changing rubidium for embeddium and oculus the game crashes after entering a world

### Log File

[crash-2024-01-03_22.09.03-client.txt](https://github.com/embeddedt/embeddium/files/13824811/crash-2024-01-03_22.09.03-client.txt)

[latest.log](https://github.com/embeddedt/embeddium/files/13824804/latest.log)

**Comment by embeddedt** [comment] 2024-01-04 01:19
Duplicate of https://github.com/embeddedt/embeddium/issues/111

**Closed as not planned by embeddedt** 2024-01-04 01:19 UTC
