### ISSUE TITLE
Invisible animated or interactive objects

### ISSUE THREAD

**Issue by RapinaX** [FiniteReality/embeddium#259] opened 2024-04-04 19:09 UTC
### Bug Description

I am using the Eureka Ships mod and I noticed this error caused by optimizer mods such as (Optifine, Rubidium, Embeddium and Embeddium++)

Any Block that has animation or is interactive becomes invisible if it is part of a ship created by (Eureka mod)

I have seen videos of other players who do not have this problem with animated blocks and I do not understand how it happens to me when using any of the mentioned ones (performance mods)
Is there a way to fix this and keep the animations?

The eureka mod works normally without any other mod but when any of the others this happens and playing without an optimizer causes a drop in FPS

I am a Forge user

Screenshot: 
![2024-04-04_13 18 40](https://github.com/embeddedt/embeddium/assets/166059814/40f953cd-0310-4452-b1bb-d4820e8b0ea6)
![2024-04-04_13 21 35](https://github.com/embeddedt/embeddium/assets/166059814/f28a1c42-ebed-4fab-86ea-7e16b7905e0d)

### Reproduction Steps

Simply install the Eureka mod and its requirements (all updated) and combine it with Embeddium or any optimizer (any version).

forge version: 47.2.0 for 1.20.1

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/14876122/latest.log)

**Comment by embeddedt** [comment] 2024-04-04 19:44
This issue should already be fixed in the latest version of Embeddium (0.3.12+).

**Comment by RapinaX** [comment] 2024-04-04 23:27
> This issue should already be fixed in the latest version of Embeddium (0.3.12+).

I just went from 0.3.11 to 0.3.12 (Forge)

It didn't work :(

I don't understand why this happens to animated blocks only when I install an optimizer.

**Comment by embeddedt** [comment] 2024-04-06 03:11
I am not able to reproduce this issue with only the aforementioned mods installed. I built a ship identical to yours and assembled it using the oak ship helm.

![2024-04-05_23 08 58](https://github.com/embeddedt/embeddium/assets/42941056/05e74a45-18ea-4312-807a-5542b56b9da4)

Please triple-check that you are using the appropriate version of Embeddium, as this is known to be an issue in older versions.

> I don't understand why this happens to animated blocks only when I install an optimizer.

This is because Valkyrien Skies makes many changes to chunk rendering in order to render their ships, which requires them to write custom patches for both vanilla & optimization mods (and these patches may have issues).

**Comment by RapinaX** [comment] 2024-04-07 04:37
> I am not able to reproduce this issue with only the aforementioned mods installed. I built a ship identical to yours and assembled it using the oak ship helm.
> 
> ![2024-04-05_23 08 58](https://private-user-images.githubusercontent.com/42941056/320173152-05e74a45-18ea-4312-807a-5542b56b9da4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NjQ2ODIsIm5iZiI6MTcxMjQ2NDM4MiwicGF0aCI6Ii80Mjk0MTA1Ni8zMjAxNzMxNTItMDVlNzRhNDUtMThlYS00MzEyLTgwN2EtNTU0MmI1NmI5ZGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA0MzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNDU0M2NhNGI2ZTkxOWYxYTJlZWVmMTc5YjAyYWFhMWEzYmVlMzUzYzQ3NjgzMTYzYjhhNTg0YTIzOTFkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HjJj0AtDtYr9NOta6Yv04ztL_fvRThgYw8uBxItfKSA)
> 
> Please triple-check that you are using the appropriate version of Embeddium, as this is known to be an issue in older versions.
> 
> > I don't understand why this happens to animated blocks only when I install an optimizer.
> 
> This is because Valkyrien Skies makes many changes to chunk rendering in order to render their ships, which requires them to write custom patches for both vanilla & optimization mods (and these patches may have issues).

Already solved. The new version 0.3.12 works as long as (entity culling) is disabled for animated blocks and (block face culling) is disabled for block faces.

**Closed as completed** 2024-04-07 13:29 UTC
Labels: cannot reproduce
